warning: Cannot check if git requires authentication.
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simpleapp
      app.kubernetes.io/component: simpleapp
      app.kubernetes.io/instance: simpleapp
    name: simpleapp
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simpleapp
      app.kubernetes.io/component: simpleapp
      app.kubernetes.io/instance: simpleapp
    name: simpleapp
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: simpleapp:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/murilloo/redhat-ex180-exam-preparation/
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.4-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: MXBCMWWmdi-_rjtBq9y1
      type: GitHub
    - generic:
        secret: Bdb-iXmj5QR_G0NUJ0Vx
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"simpleapp:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"simpleapp\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simpleapp
      app.kubernetes.io/component: simpleapp
      app.kubernetes.io/instance: simpleapp
    name: simpleapp
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: simpleapp
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: simpleapp
      spec:
        containers:
        - image: ' '
          name: simpleapp
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simpleapp
      app.kubernetes.io/component: simpleapp
      app.kubernetes.io/instance: simpleapp
    name: simpleapp
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: simpleapp
  status:
    loadBalancer: {}
kind: List
metadata: {}
